### ISSUE TITLE
提示地址输入错误

### ISSUE THREAD

**Issue by jerrysiuu** [KaguraChen/BilibiliPicture#1]
从浏览器直接复制的专栏地址和空间地址都提示地址输入错误

**Comment by KaguraChen** [comment]
我这边本地运行并没有问题，你可以通过在summit函数中的except语句里打印出错误信息来定位错误来源。

**Comment by jerrysiuu** [comment]
您好，我已经收到了您发给我的邮件，我会尽快处理。

**Comment by jerrysiuu** [comment]
您好，我已经收到了您发给我的邮件，我会尽快处理。
